/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#10131a",
        "surface-dim": "#10131a",
        "surface-bright": "#363940",
        "surface-container-lowest": "#0b0e14",
        "surface-container-low": "#191c22",
        "surface-container": "#1d2026",
        "surface-container-high": "#272a31",
        "surface-container-highest": "#32353c",
        "surface-variant": "#32353c",
        "surface-tint": "#adc6ff",
        "on-surface": "#e1e2eb",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#e1e2eb",
        "inverse-on-surface": "#2e3037",
        "background": "#10131a",
        "on-background": "#e1e2eb",
        "primary": "#adc6ff",
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "secondary": "#fff9ef",
        "on-secondary": "#3a3000",
        "secondary-container": "#ffdb3c",
        "on-secondary-container": "#725f00",
        "secondary-fixed": "#ffe16d",
        "secondary-fixed-dim": "#e9c400",
        "tertiary": "#4edea3",
        "on-tertiary": "#003824",
        "tertiary-container": "#00a572",
        "on-tertiary-container": "#00311f",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "outline": "#8c909f",
        "outline-variant": "#424754",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "Noto Sans KR", "sans-serif"],
        mono: ["Geist", "monospace"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
      },
      spacing: {
        "sidebar": "280px",
        "sidebar-collapsed": "80px",
        "gutter": "24px",
        "topnav": "64px",
      },
      borderRadius: {
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      backdropBlur: {
        "panel": "20px",
      },
    },
  },
  plugins: [],
}
